* Babelized Emacs User Initialization File
This is my portable Emacs configuration, to make it easy for me to have the same Emacs across machines, VMs, etc.

** Initial Package Setup
Just for two things:
- Adds MELPA to package-archives. Pretty much all the useful extra packages are there.
#+BEGIN_SRC emacs-lisp
(require 'package)
(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")))
(package-initialize)
#+END_SRC

- Install use-package if it's not already installed. Note the call to package-refresh-contents to make sure this works with freshly installed Emacs too.
#+BEGIN_SRC emacs-lisp
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)
(setq use-package-always-ensure t)
#+END_SRC

** Common Configuration
Common configuration across all tasks.

*** Separate Customize Settings
The settings written by Customize aren't meant to be edited manually, so it's better to separate them into another file. Also, create the custom.el file if it doesn't already exist.
#+BEGIN_SRC emacs-lisp
(defconst custom-file-path (expand-file-name "custom.el" user-emacs-directory))
(unless (file-exists-p custom-file-path)
  (write-region "" nil custom-file-path))
(setq custom-file custom-file-path)
(load custom-file)
#+END_SRC

*** Miscellaneous
Start in home directory.
#+BEGIN_SRC emacs-lisp
(setq default-directory "~/")
#+END_SRC

Yes, when I quit, I do want to kill processes. No need to ask me.
#+BEGIN_SRC emacs-lisp
(setq confirm-kill-processes nil)
#+END_SRC

*** UI Settings
The [Doom Themes](https://github.com/hlissner/emacs-doom-themes) are nice. I like the Nord Light theme.
#+BEGIN_SRC emacs-lisp
(use-package doom-themes
  :config
  ;; Global settings (defaults)
  (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
        doom-themes-enable-italic t) ; if nil, italics is universally disabled
  (load-theme 'doom-nord-light t)

  ;; Enable flashing mode-line on errors
  (doom-themes-visual-bell-config)
    
  ;; Corrects (and improves) org-mode's native fontification.
  (doom-themes-org-config))
#+END_SRC

Disable the startup screen.
#+BEGIN_SRC emacs-lisp
(setq inhibit-startup-message t)
#+END_SRC

Disable the menu, scrollbar, and toolbar. They reset initial frame's size so have to be done first.
#+BEGIN_SRC emacs-lisp
(menu-bar-mode nil)
(scroll-bar-mode -1)
(tool-bar-mode -1)
#+END_SRC

Set initial frame to handle 160x48 characters, and center it on the screen.
#+BEGIN_SRC emacs-lisp
;; Set initial frame size and position
(defun set-initial-frame (max-chars-per-line max-no-of-lines)
  (let* ((frame-width (* (window-font-width) max-chars-per-line))
	 (frame-height (* (window-font-height) max-no-of-lines))
	 (frame-left (truncate (/ (- (display-pixel-width) frame-width) 2)))
	 (frame-top (truncate (/ (- (display-pixel-height) frame-height) 2))))
    (set-frame-position (selected-frame) frame-left frame-top)
    (set-frame-size (selected-frame) frame-width frame-height t)))
(when (display-graphic-p)
  (setq frame-resize-pixelwise t)
  (set-initial-frame 160 48))
#+END_SRC

Line and column modes.
#+BEGIN_SRC emacs-lisp
(column-number-mode 1)
(global-hl-line-mode t)
(global-linum-mode)
#+END_SRC

** Packages
Packages I want to install with every fresh Emacs.
#+BEGIN_SRC emacs-lisp
(use-package magit
  :ensure t)

(use-package company
  :ensure t
  :config
  (progn
    (add-hook 'after-init-hook 'global-company-mode)))

(use-package ivy
  :ensure t)

(use-package swiper
  :ensure t)
#+END_SRC
